version: "3.8"

services:
  n8n:
    image: docker.n8n.io/n8nio/n8n
    container_name: n8n_1
    ports:
      - "5678:5678"
    volumes:
      - n8n_data_1:/home/node/.n8n
    command: start --tunnel

volumes:
  n8n_data_1:
